FROM python:3.10-slim

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN apt-get update \
    && apt-get install libfbclient2 -y \
    && apt-get install bash \
    && apt-get clean

RUN pip install -r /app/requirements.txt \
    && rm -rf /root/.cache/pip

COPY ./app /app

EXPOSE 5010

CMD ["uvicorn" "app.main:app" "--host 0.0.0.0" "--port 5010"]
