FROM python:3.10-slim

WORKDIR /app

USER root:root

RUN apt-get update \
    && apt-get install bash \
    && apt-get clean

RUN apt-get install curl -y

RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

RUN az config set core.encrypt_token_cache=false

COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt \
    && rm -rf /root/.cache/pip

RUN pip install -U langchain-community

COPY . /app

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
