FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app/

# Copy the rest of the application code to the container
COPY . /app/
COPY package*.json /app/

# Build the React app
RUN npm run build

# Install dependencies
RUN npm install

# Expose a port (e.g., 3000) for the application
EXPOSE 3000

# Start the React app when the container runs
CMD ["npm", "start"]
